### ISSUE TITLE
在代码加入React.StrictMode报错，这个可以修复吗？

### ISSUE THREAD

**Issue by learning-go123** [i18n-pro/react#1]
demo：
https://codesandbox.io/p/github/i18n-pro/react-demo/csb-8ytpjs/draft/condescending-glitter?file=%2Fsrc%2FApp.tsx%3A140%2C2

错误：
<img width="636" alt="image" src="https://github.com/i18n-pro/react/assets/88469563/a2bd50c5-a96b-4654-a491-2b083447ea65">

**Comment by eyelly-wu** [comment]
@learning-go123 hi，根据官方的文档说明得知，使用严格模式会让内部组件渲染两次，上面截图中的警告，就是因为组件 `I18nProvider` 渲染了两次，组件内部根据同一个 namespace 初始化两次导致的
<img width="1230" alt="image" src="https://github.com/i18n-pro/react/assets/24505069/736292ea-ec24-4584-a371-bc76ea4c0122">

因此说明，组件本身是没有问题的，如果非要在严格模式下去掉警告的话，`StrictMode` 就不要包裹 `I18nProvider` 这层，类似如下：
```
render(
  <I18nProvider {...initI18nState}>
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </I18nProvider>,
  document.getElementById('root') as HTMLElement,
)
```

**Comment by learning-go123** [comment]
好的，懂了 谢谢大佬
